### ISSUE TITLE
Icons being on the wrong slot

### ISSUE THREAD

**Issue by RazorLeaf16** [hiimjustin000/MoreIcons#2]
I'm having this issue where icons are in the wrong slot and on a diagonal row on each slot.
![issue](https://github.com/user-attachments/assets/2d90b5d4-9476-4d13-b25e-e2b4a25f89e3)

**Comment by hiimjustin000** [comment]
you probably have duplicate icons.

**Comment by hiimjustin000** [comment]
actually, how many icons are in config/hiimjustin000.more_icons/icon?

**Comment by RazorLeaf16** [comment]
1,544 (im using my friends 3k icon mix)

**Comment by RazorLeaf16** [comment]
but i can confirm they're not dupped icons
![not a dupe1](https://github.com/user-attachments/assets/d3666ea9-7fc9-4f67-ab35-836956e39a5d)
![not a dupe2](https://github.com/user-attachments/assets/55ceb67f-71f9-4066-be7f-cf6d663710ef)

**Comment by RazorLeaf16** [comment]
and when i checked the folder it shows that all icons are in order
![p](https://github.com/user-attachments/assets/ab1a3042-5ce6-423c-ada4-4a33daadc6a6)

**Comment by RazorLeaf16** [comment]
forgot to mention that a hand full of icons from slot 1 get put at the end

**Comment by hiimjustin000** [comment]
You probably have many icons with the same textures. Click on the icons to see if they have different names.

**Comment by RazorLeaf16** [comment]
i think i figured out my issue, so apparently the icons are getting put after 1_9 for example player_16 is put next to player_159

**Comment by RazorLeaf16** [comment]
its kinda hard to explain but i think its putting icons to where it is via number (iic)

**Comment by hiimjustin000** [comment]
yeah it's ordered like that

**Comment by RazorLeaf16** [comment]
yeah, but I don't think it's supposed to do that..

**Comment by fibberclip** [comment]
isn't this way of ordering a LOT better though?? if you're mixing icons from different packs it makes more sense that if you, for example, have:

techPlayer_01
techPlayer_05
techPlayer_06
& then
bunnymixPlayer_03
bunnymixPlayer_09

it's a lot better to have all icons with a similar filename (in this case, icons all from a same pack) all close to eachother in the icon selection screen, rather than have them all randomly placed with icons that aren't even related

**Comment by hiimjustin000** [comment]
Fixed in v1.1.1 (4d18bce)
